### ISSUE TITLE
Attach a read only volume when running a container with specific data

### ISSUE THREAD

**Issue by donaldknoller** [macromarkets-xyz/x#5]
When running a container, attach a volume that is read only with the following properties:
1. Includes a folder called `raw_price_data`
2. Inside the folder, there is a file called `data_feed.csv` which is a csv file that contains dummy data with a column called `TIMESTAMP` which is a timestamp in ISO 8601 format and `PRICE` which is a randomly generated number
3. The docker image should NOT be able to modify the .csv file . Test a version of the docker image which attempts this to manually verify

**Comment by chiefchimp** [comment]
Updated and pushed to main. No idea how to do #3 :)
